import { useAiInsights } from '@/hooks/useCommandCenter';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Brain, AlertCircle, TrendingUp, HelpCircle, Activity, Sparkles, RefreshCw, Play } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface OperationalInsightsDashboardProps {
  storeId?: string;
}

export default function OperationalInsightsDashboard({ storeId }: OperationalInsightsDashboardProps) {
  const { data: insights = [], isLoading, refreshInsights, isRefreshing } = useAiInsights(storeId);
  const { toast } = useToast();

  const handleRefresh = async () => {
    try {
      await refreshInsights();
      toast({
        title: 'Insights Refreshed',
        description: 'Successfully computed latest operational AI insights.'
      });
    } catch (err: any) {
      toast({
        title: 'Refresh Failed',
        description: err.message,
        variant: 'destructive'
      });
    }
  };

  const getInsightIcon = (type: string) => {
    switch (type?.toLowerCase()) {
      case 'risk':
        return <AlertCircle className="w-5 h-5 text-rose-400" />;
      case 'opportunity':
        return <TrendingUp className="w-5 h-5 text-emerald-400" />;
      default:
        return <HelpCircle className="w-5 h-5 text-cyan-400" />;
    }
  };

  const getInsightTypeColor = (type: string) => {
    switch (type?.toLowerCase()) {
      case 'risk':
        return 'bg-rose-500/10 text-rose-300 border-rose-500/20';
      case 'opportunity':
        return 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20';
      default:
        return 'bg-cyan-500/10 text-cyan-300 border-cyan-500/20';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-cyan-400">Operational Intelligence</h3>
          <p className="text-xs text-blue-200">Continuous risk and revenue optimization insights generated by autonomous backend agents.</p>
        </div>
        <Button
          onClick={handleRefresh}
          disabled={isRefreshing}
          className="neon-border bg-purple-500/20 text-purple-300 hover:bg-purple-500/30"
          size="sm"
        >
          <RefreshCw className={`w-3.5 h-3.5 mr-2 ${isRefreshing ? 'animate-spin' : ''}`} />
          Run Insight Generator
        </Button>
      </div>

      {isLoading ? (
        <div className="text-center py-12 text-blue-300">
          Loading AI insights...
        </div>
      ) : insights.length === 0 ? (
        <Card className="neon-border bg-slate-900/40 border-dashed p-12 text-center">
          <Brain className="w-12 h-12 text-blue-400/60 mx-auto mb-3 animate-pulse" />
          <h4 className="font-semibold text-blue-100 text-lg">No Operational Insights</h4>
          <p className="text-blue-300 text-sm max-w-md mx-auto mt-1">
            There are no machine learning insights computed for this location. Click "Run Insight Generator" above to compile.
          </p>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {insights.map((insight) => (
            <Card key={insight.id} className="neon-border bg-slate-900/50 flex flex-col justify-between">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-center gap-2">
                    {getInsightIcon(insight.type)}
                    <Badge variant="outline" className={`capitalize text-[9px] font-bold ${getInsightTypeColor(insight.type)}`}>
                      {insight.type}
                    </Badge>
                  </div>
                  {insight.relevance_score && (
                    <Badge className="neon-border bg-purple-500/25 text-purple-300 border-purple-500/30 font-mono text-[10px]">
                      Relevance: {Math.round(insight.relevance_score * 100)}%
                    </Badge>
                  )}
                </div>
                <CardTitle className="text-sm font-bold text-blue-100 mt-2">{insight.title}</CardTitle>
                <CardDescription className="text-xs text-blue-200 leading-relaxed pt-1">
                  {insight.content}
                </CardDescription>
              </CardHeader>
              <CardContent className="pt-0 space-y-3">
                {insight.metric_value !== null && insight.metric_value !== undefined && (
                  <div className="text-[10px] text-muted-foreground flex items-center gap-1">
                    <Activity className="w-3.5 h-3.5 text-cyan-400" />
                    Metric Value: <span className="font-mono text-foreground font-semibold">{insight.metric_value}</span>
                  </div>
                )}
                
                {insight.recommended_action && (
                  <div className="p-3 rounded-lg bg-cyan-500/5 border border-cyan-500/10 text-xs">
                    <span className="font-bold text-cyan-400 block mb-1 flex items-center gap-1">
                      <Sparkles className="w-3.5 h-3.5" /> Recommended Action:
                    </span>
                    <p className="text-blue-100 leading-relaxed font-medium">{insight.recommended_action}</p>
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
