// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyzwtoxrosfdheqehsvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5end0b3hyb3NmZGhlcWVoc3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTIzNjgsImV4cCI6MjA2NjE2ODM2OH0.6QwGhDyNCafA8J1PzkvopLVorbkYw0hrp8nB5SUKKGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);